dataset: UCSB
node_num: 38
window_size: 10
max_thres: 2000
test_rate: 0.1
in_features: 1
out_features: 64
lstm_features: 128
disc_hidden: 512
pretrain_learning_rate: 0.005
d_learning_rate: 0.00001
g_learning_rate: 0.00001
batch_size: 64
pretrain_epoches: 10
gan_epoches: 2
gradient_clip: 5.0
weight_clip: 0.01
epsilon: 0.01